# Makefile for Computer Graphics
# Interterm 2009
# Assignment 4
# Joe Smith
# 0949140
# 01/16/09

CC=gcc 
CFLAGS=-Wall -lglut
.PHONY: clean

all: part1 part2

part1: part1.c

part2: part2.c

clean:
	rm -f part1 part2
